apitransporte/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('v1/solicitud', views.listado_solicitud, name='lista_solicitud'),
    path('v1/solicitud/<id>', views.vista_solicitud, name='vista_solicitud'),
]

sis_transporte/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transporte.urls')),
    path('api/', include('apitransporte.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

transporte/urls.py
from django.urls import path
from .views import index,crear_solicitud, listar_solicitud, logouts, modificar_solicitud
urlpatterns = [
    path('', index, name='transporte_index'),
    path('contacto/',crear_solicitud, name='crear_solicitud'),
    path('listado/', listar_solicitud, name='listar_solicitud'),
    path('accounts/logout/', logouts, name='logout'),
    path('modificar_solicitud/<str:codigo_seguimiento>/', modificar_solicitud, name='modificar_solicitud'),
]

apitransporte/models.py
from django.db import models

# Create your models here.

transporte/models.py
from django.db import models
from django.utils.crypto import get_random_string

class SolicitudTransporte(models.Model):
    ESTADOS_CHOICES = (
        ('pendiente', 'Pendiente'),
        ('en_proceso', 'En Proceso'),
        ('entregado', 'Entregado'),
        ('cancelado', 'Cancelado'),
    )
    codigo_seguimiento = models.CharField(max_length=20, unique=True, primary_key=True)
    persona_origen = models.CharField(max_length=100)
    direccion_origen = models.CharField(max_length=255)
    persona_destino = models.CharField(max_length=100)
    direccion_destino = models.CharField(max_length=255)
    descripcion = models.TextField()
    estado = models.CharField(max_length=20, choices=ESTADOS_CHOICES, default='pendiente')

    def __str__(self):
        return f"Solicitud {self.codigo_seguimiento} - {self.estado}"

    def save(self, *args, **kwargs):
        if not self.codigo_seguimiento:
            # Genera un código único
            self.codigo_seguimiento = self.generar_codigo_unico()
        super(SolicitudTransporte, self).save(*args, **kwargs)

    @staticmethod
    def generar_codigo_unico():
        length = 20
        while True:
            codigo = get_random_string(length=length)
            if not SolicitudTransporte.objects.filter(codigo_seguimiento=codigo).exists():
                break
        return codigo

transporte/forms.py
from django import forms
from .models import SolicitudTransporte

class SolicitudTransporteForm(forms.ModelForm):
    class Meta:
        model = SolicitudTransporte
        exclude = ['codigo_seguimiento']

apitransporte/views.py
from django.shortcuts import render

# Create your views here.
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from transporte.models import SolicitudTransporte
from .serializers import SolicitudTransporteSerializer
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from rest_framework import status

@csrf_exempt #para que no pida tocken de acceso
@api_view(['GET','POST']) #solo acepte perticiones GET
def listado_solicitud(request):
    if request.method == 'GET':
        solicitud = SolicitudTransporte.objects.all()
        serializer = SolicitudTransporteSerializer(solicitud, many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = SolicitudTransporteSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.data, status=status.HTTP_400_BAD_REQUEST)
        
@csrf_exempt #para que no pida tocken de acceso
@api_view(['GET','PUT','DELETE']) #solo acepte perticiones GET
def vista_solicitud(request, id):
    if request.method == 'GET':
        try:
            solicitud = SolicitudTransporte.objects.get(codigo_seguimiento=id)
        except SolicitudTransporte.DoesNotExist:
            return Response(status=status.HTPP_404_NOT_FOUND)
        serializer = SolicitudTransporteSerializer(solicitud)
        return Response(serializer.data)
    elif request.method == 'PUT':
        try:
            solicitud = SolicitudTransporte.objects.get(codigo_seguimiento=id)
        except SolicitudTransporte.DoesNotExist:
            return Response(status=status.HTPP_404_NOT_FOUND)
        data = JSONParser().parse(request)
        serializer = SolicitudTransporteSerializer(solicitud, data=data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        else:
            return Response(serializer.data, status=status.HTPP_400_BAD_REQUEST)
    elif request.method == 'DELETE':
        try:
            solicitud = SolicitudTransporte.objects.get(codigo_seguimiento=id)
        except SolicitudTransporte.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)
        solicitud.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

transporte/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import SolicitudTransporte
from .forms import SolicitudTransporteForm
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
# Create your views here.
def index(request):
    
    if request.method == 'POST':
        # buscar el codigo de seguimiento
        codigo_seguimiento = request.POST.get('codigo_seguimiento', '')
        # Realiza la búsqueda en la base de datos
        resultados = SolicitudTransporte.objects.filter(codigo_seguimiento=codigo_seguimiento).first()
        return render(request, 'index.html', {'resultados': resultados, 'codigo_seguimiento': codigo_seguimiento})
    
    return render(request, 'index.html')
@csrf_protect
def crear_solicitud(request):
    data = {
        'form': SolicitudTransporteForm()
    }
    if request.method == 'POST':
        solicitud = SolicitudTransporteForm(data=request.POST)
        if solicitud.is_valid():
            solicitud.save()
        else:
            data["form"] = solicitud

    return render(request, 'crearsoli.html', data)

def listar_solicitud(request):
    # Recuperar el término de búsqueda del request GET
    codigo_seguimiento_query = request.GET.get('codigo_seguimiento', '')

    # Filtrar las solicitudes por código de seguimiento si se proporciona un término de búsqueda
    if codigo_seguimiento_query:
        solicitudes = SolicitudTransporte.objects.filter(codigo_seguimiento__icontains=codigo_seguimiento_query)
        print(solicitudes)  # Depuración para ver qué se recupera
    else:
        solicitudes = SolicitudTransporte.objects.all()

    # Pasar las solicitudes al contexto de la plantilla HTML
    return render(request, 'listarsoli.html', {'solicitudes': solicitudes})

def logouts(request):
    logout(request)
    return redirect('transporte_index')

def modificar_solicitud(request, codigo_seguimiento):
    codigo_seguimiento = get_object_or_404(SolicitudTransporte, codigo_seguimiento=codigo_seguimiento)
    if request.method == "POST":
        nuevo_estado = request.POST.get('estado')
        codigo_seguimiento.estado = nuevo_estado
        codigo_seguimiento.save()
        return redirect('listar_solicitud')

    return render(request, 'modificar_solicitud.html', {'solicitud': codigo_seguimiento, 'ESTADOS_CHOICES': SolicitudTransporte.ESTADOS_CHOICES})

transporte/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Transporte</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="{% static 'app/css/index.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg" style="background-color: orange;">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'transporte_index' %}"><img src="{% static 'app/img/logo_cagafacil.png' %}" alt="Mi imagen" style="width: 50px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'transporte_index' %}">Inicio</a>
                        </li>
                        {% if perms.transporte.change_solicitudtransporte %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'crear_solicitud' %}">Crear solicutud</a>
                            </li>
                        {% endif %}
                        {% if perms.transporte.view_solicitudtransporte%}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'listar_solicitud' %}">Listar solicutud</a>
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">@{{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar session</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar sesion</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class="content container">
            {% block content %}
            {% endblock %}
        </div>

        <script src="{% static 'fontawesomepro/js/all.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

transporte/templates/buscar.html
<!doctype html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Transporte</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="{% static 'app/css/index.css' %}" rel="stylesheet">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg" style="background-color: orange;">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'transporte_index' %}"><img src="{% static 'app/img/logo_cagafacil.png' %}" alt="Mi imagen" style="width: 50px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'transporte_index' %}">Inicio</a>
                        </li>
                        {% if perms.transporte.change_solicitudtransporte %}
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{% url 'crear_solicitud' %}">Crear solicutud</a>
                            </li>
                        {% endif %}
                        {% if perms.transporte.view_solicitudtransporte%}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'listar_solicitud' %}">Listar solicutud</a>
                        </li>
                        {% endif %}
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="#">@{{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Cerrar session</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Iniciar sesion</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>      

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

transporte/templates/crearsoli.html
{% extends 'base.html' %}{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}
    <div class="container mt-1">
        <div class="row">
            <div class="card col-md-6">
                <div class="card-body form-group">
                    <h2>Crear solicitud!</h2>
                    <form action="" class="form-group-sm" method="post">
                        {% csrf_token %}
                        {{ form | crispy }}
                        <br>
                        <div class="d-flex justify-content-end">
                            <button type="submit" id="btnEnviar" class="btn btn-secondary">Enviar</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

transporte/templates/index.html
{% extends 'base.html' %}{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}
    <div class="container mt-5" id="trackingForm">
        <div class="row">
            <div class="col-md-6">
                <div class="container mt-5 row">
                    <h2 class="display-4">CargaFacil</h2>
                </div>
                <form method="post" action="">
                    <div class="mb-3">
                        {% csrf_token %}
                        <h4 class=""><label for="codigo_seguimiento" class="form-label">Ve el estado de tu producto</label><h4>
                        <div class="input-group">
                        <input type="text" class="form-control" name="codigo_seguimiento" id="codigo_seguimiento" placeholder="Ingresa el código del pedido">
                        <button type="submit" class="btn btn-light"id="miBoton"><img src="{% static 'app/img/icons8-lupa-50.png' %}" alt="Mi imagen"></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div id="resultado">
    {% if resultados %}
    <div class="container mt-6">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item">Nombre: {{ resultados.persona_origen }}</li>
                <li class="list-group-item">Codigo: N° {{ resultados.codigo_seguimiento }}</li>
                <li class="list-group-item">Estado: {{ resultados.get_estado_display }}</li>
            </ul>
        </div>
    </div>
    {% endif %}
{% endblock %}

transporte/templates/listarsoli.html
{% extends 'base.html' %}{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}
    <form method="get" action="{% url 'listar_solicitud' %}">
        <div class="form-group" style="margin-top: 10px;">
            <input type="text" class="form-control" name="codigo_seguimiento" placeholder="Buscar por Código de Seguimiento">
        </div>
        <button type="submit" class="btn btn-primary" style="margin-top: 10px;">Buscar</button>
    </form>
    <table class="table table-md-responsive" style="margin-top: 10px;">
        <thead class="thead-light">
        <tr>
            <th>Código de Seguimiento</th>
            <th>Persona Origen</th>
            <th>Dirección Origen</th>
            <th>Persona Destino</th>
            <th>Dirección Destino</th>
            <th>Descripción</th>
            <th>Estado</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
            {% for s in solicitudes %}
            <tr>
                <td>{{ s.codigo_seguimiento }}</td>
                <td>{{ s.persona_origen }}</td>
                <td>{{ s.direccion_origen }}</td>
                <td>{{ s.persona_destino }}</td>
                <td>{{ s.direccion_destino }}</td>
                <td>{{ s.descripcion }}</td>
                <td>{{ s.estado }}</td>
                <td>
                    <a href="{% url 'modificar_solicitud' s.codigo_seguimiento %}" class="btn btn-primary">Modificar Estado</a>
                </td>
            </tr>
            {% empty %}
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

transporte/templates/modificar_solicitud.html
{% extends 'base.html' %}{% block content %}
    {% load static %}
    {% load crispy_forms_tags %}
    <div class="container">
        <h2>Modificar Estado de la Solicitud</h2>
        <form method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="codigoSeguimiento">Código de Seguimiento</label>
            <input type="text" class="form-control" id="codigoSeguimiento" value="{{ solicitud.codigo_seguimiento }}" readonly>
          </div>
          <div class="form-group">
            <label for="estado">Estado</label>
            <select class="form-control" id="estado" name="estado">
              {% for codigo, nombre in ESTADOS_CHOICES %}
              <option value="{{ codigo }}" {% if solicitud.estado == codigo %}selected{% endif %}>{{ nombre }}</option>
              {% endfor %}
            </select>
          </div>
          <br>
          <button type="submit" class="btn btn-success">Guardar Cambios</button>
        </form>
      </div>
{% endblock %}